M48
; DRILL file {KiCad 7.0.9} date Tue 28 Nov 2023 01:05:12 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-28T13:05:12-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
%
G90
G05
T1
X4.4Y-1.8
X4.4Y-2.0
X4.4Y-2.8
X4.4Y-3.0
T2
X5.0Y-1.9
X5.0Y-2.0
X5.0Y-2.8
X5.0Y-2.9
T0
M30
